version: '3.6'
services:

  openldap:
    env_file: .env
    image: osixia/openldap:latest
    restart: always
    container_name: openldap
    environment:
      TZ: Asia/Seoul
      LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    volumes:
      - ./slapd/config:/etc/ldap/slapd.d
      - ./slapd/database:/var/lib/ldap
    ports:
      - 389:389
      - 636:636
    networks:
      - ldapnetwork

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: phpldapadmin
    environment:
      TZ: Asia/Seoul
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    #volumes:
    #  - ./pla/config:/container/service/phpldapadmin/assets/config
    #  - ./pla/phpldapadmin:/var/www/phpldapadmin
    ports:
      - 8080:80
      - 8443:443
    links:
      - "openldap:openldap"
    networks:
      - ldapnetwork

networks:
  ldapnetwork:
